"""Initial migration

Revision ID: 37a1d784bcb0
Revises: 
Create Date: 2026-07-17 19:35:43.359526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37a1d784bcb0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedbacks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.JSON(), nullable=True),
    sa.Column('ignored_sources', sa.JSON(), nullable=True),
    sa.Column('corrections', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedbacks_session_id'), 'feedbacks', ['session_id'], unique=False)
    op.create_table('graph_edges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('properties', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graph_edges_source_id'), 'graph_edges', ['source_id'], unique=False)
    op.create_index('ix_graph_edges_source_type', 'graph_edges', ['source_id', 'type'], unique=False)
    op.create_index(op.f('ix_graph_edges_target_id'), 'graph_edges', ['target_id'], unique=False)
    op.create_index('ix_graph_edges_target_type', 'graph_edges', ['target_id', 'type'], unique=False)
    op.create_index(op.f('ix_graph_edges_type'), 'graph_edges', ['type'], unique=False)
    op.create_table('graph_nodes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('properties', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graph_nodes_name'), 'graph_nodes', ['name'], unique=False)
    op.create_index(op.f('ix_graph_nodes_type'), 'graph_nodes', ['type'], unique=False)
    op.create_index('ix_graph_nodes_type_name', 'graph_nodes', ['type', 'name'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retrieval_params',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('dense_weight', sa.Float(), nullable=False),
    sa.Column('sparse_weight', sa.Float(), nullable=False),
    sa.Column('chunk_size', sa.Integer(), nullable=False),
    sa.Column('chunk_overlap', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('organization', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('applied_date', sa.Date(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('citations', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_messages')
    op.drop_table('chat_sessions')
    op.drop_table('applications')
    op.drop_table('retrieval_params')
    op.drop_table('profiles')
    op.drop_index('ix_graph_nodes_type_name', table_name='graph_nodes')
    op.drop_index(op.f('ix_graph_nodes_type'), table_name='graph_nodes')
    op.drop_index(op.f('ix_graph_nodes_name'), table_name='graph_nodes')
    op.drop_table('graph_nodes')
    op.drop_index(op.f('ix_graph_edges_type'), table_name='graph_edges')
    op.drop_index('ix_graph_edges_target_type', table_name='graph_edges')
    op.drop_index(op.f('ix_graph_edges_target_id'), table_name='graph_edges')
    op.drop_index('ix_graph_edges_source_type', table_name='graph_edges')
    op.drop_index(op.f('ix_graph_edges_source_id'), table_name='graph_edges')
    op.drop_table('graph_edges')
    op.drop_index(op.f('ix_feedbacks_session_id'), table_name='feedbacks')
    op.drop_table('feedbacks')
    # ### end Alembic commands ###
