#!/usr/bin/env bash

# Bootstrap script for NORAY local environment on macOS/Linux.
# This script will:
# - Verify prerequisites (Python, Node.js, Git)
# - Create a Python virtual environment
# - Install Python dependencies
# - Install Node dependencies
# - Initialize default configuration

set -e

echo -e "\033[1;36m🚀 Starting NORAY Environment Bootstrap...\033[0m"

# 1. Verify Prerequisites
echo -e "\n\033[1;34m[1/5] Checking prerequisites...\033[0m"
MISSING=0

check_cmd() {
    echo -n "Checking for $1... "
    if command -v "$2" >/dev/null 2>&1; then
        echo -e "\033[1;32m✓ Found\033[0m"
    else
        echo -e "\033[1;31m✗ Missing\033[0m"
        MISSING=1
    fi
}

check_cmd "Python (3.10+)" "python3"
check_cmd "Node.js" "node"
check_cmd "npm" "npm"
check_cmd "Git" "git"

if [ $MISSING -eq 1 ]; then
    echo -e "\033[1;31mPlease install missing prerequisites before continuing.\033[0m"
    exit 1
fi

# 2. Python Virtual Environment
echo -e "\n\033[1;34m[2/5] Setting up Python virtual environment...\033[0m"
if [ ! -d ".venv" ]; then
    echo "Creating virtual environment..."
    python3 -m venv .venv
else
    echo "Virtual environment already exists."
fi

echo "Activating virtual environment..."
source .venv/bin/activate

# 3. Install Python Dependencies
echo -e "\n\033[1;34m[3/5] Installing Python dependencies...\033[0m"
python -m pip install --upgrade pip
if [ -f "pyproject.toml" ]; then
    pip install -e .
else
    echo -e "\033[1;33mWarning: pyproject.toml not found, skipping Python package installation.\033[0m"
fi

# 4. Install Node Dependencies
echo -e "\n\033[1;34m[4/5] Installing Node.js dependencies...\033[0m"
if [ -d "frontend" ]; then
    cd frontend
    npm install
    cd ..
else
    echo -e "\033[1;33mWarning: frontend directory not found, skipping Node.js package installation.\033[0m"
fi

# 5. Initialize Configuration
echo -e "\n\033[1;34m[5/5] Initializing configuration...\033[0m"
if [ ! -f ".env" ]; then
    echo "Generating default .env file..."
    cat > .env << EOL
# NORAY Environment Configuration
# Automatically generated by setup.sh

ENVIRONMENT=development

# Database Settings
POSTGRES_USER=noray
POSTGRES_PASSWORD=noray_dev
POSTGRES_DB=noray_db
POSTGRES_HOST=localhost
POSTGRES_PORT=5432

# Vector Store
QDRANT_HOST=localhost
QDRANT_PORT=6333

# Redis Cache
REDIS_HOST=localhost
REDIS_PORT=6379

# AI Gateway
# Configure at least one provider
# OLLAMA_BASE_URL=http://localhost:11434
# OPENAI_API_KEY=
# ANTHROPIC_API_KEY=
# GEMINI_API_KEY=
EOL
    echo -e "\033[1;32m.env created successfully.\033[0m"
else
    echo ".env file already exists."
fi

echo -e "\n\033[1;32m✅ NORAY Bootstrap Complete!\033[0m"
echo "To start the development environment:"
echo "  1. Start Docker services: docker-compose up -d"
echo "  2. Activate virtual environment: source .venv/bin/activate"
echo "  3. Start Python server: uvicorn api.main:app --reload"
echo "  4. Start Next.js frontend: cd frontend && npm run dev"
