<#
.SYNOPSIS
Bootstrap script for NORAY local environment on Windows.

.DESCRIPTION
This script will:
- Verify prerequisites (Python, Node.js, Git)
- Create a Python virtual environment
- Install Python dependencies
- Install Node dependencies
- Initialize default configuration
#>

Write-Host "🚀 Starting NORAY Environment Bootstrap..." -ForegroundColor Cyan

# 1. Verify Prerequisites
$prerequisites = @(
    @{ Name="Python"; Command="python --version" },
    @{ Name="Node.js"; Command="node --version" },
    @{ Name="npm"; Command="npm --version" },
    @{ Name="Git"; Command="git --version" }
)

foreach ($prereq in $prerequisites) {
    Write-Host "Checking for $($prereq.Name)..." -NoNewline
    try {
        Invoke-Expression $prereq.Command | Out-Null
        Write-Host " ✓ Found" -ForegroundColor Green
    } catch {
        Write-Host " ✗ Missing" -ForegroundColor Red
        Write-Error "Please install $($prereq.Name) before continuing."
        exit 1
    }
}

# 2. Python Virtual Environment
$venvPath = Join-Path -Path $PWD -ChildPath ".venv"
if (-not (Test-Path $venvPath)) {
    Write-Host "Creating Python virtual environment..."
    python -m venv .venv
}
Write-Host "Activating virtual environment..."
$env:Path = "$PWD\.venv\Scripts;$env:Path"

# 3. Install Python Dependencies
Write-Host "Installing Python dependencies..."
python -m pip install --upgrade pip
if (Test-Path "pyproject.toml") {
    pip install -e .
} else {
    Write-Warning "pyproject.toml not found, skipping Python package installation."
}

# 4. Install Node Dependencies
$frontendPath = Join-Path -Path $PWD -ChildPath "frontend"
if (Test-Path $frontendPath) {
    Write-Host "Installing Node.js dependencies..."
    Push-Location $frontendPath
    npm install
    Pop-Location
} else {
    Write-Warning "Frontend directory not found, skipping Node.js package installation."
}

# 5. Initialize Configuration
$envFile = Join-Path -Path $PWD -ChildPath ".env"
if (-not (Test-Path $envFile)) {
    Write-Host "Generating default .env file..."
    @"
# NORAY Environment Configuration
# Automatically generated by setup.ps1

ENVIRONMENT=development

# Database Settings
POSTGRES_USER=noray
POSTGRES_PASSWORD=noray_dev
POSTGRES_DB=noray_db
POSTGRES_HOST=localhost
POSTGRES_PORT=5432

# Vector Store
QDRANT_HOST=localhost
QDRANT_PORT=6333

# Redis Cache
REDIS_HOST=localhost
REDIS_PORT=6379

# AI Gateway
# Configure at least one provider
# OLLAMA_BASE_URL=http://localhost:11434
# OPENAI_API_KEY=
# ANTHROPIC_API_KEY=
# GEMINI_API_KEY=
"@ | Out-File $envFile -Encoding UTF8
    Write-Host ".env created successfully." -ForegroundColor Green
}

Write-Host "✅ NORAY Bootstrap Complete!" -ForegroundColor Green
Write-Host "To start the development environment:"
Write-Host "  1. Start Docker services: docker-compose up -d"
Write-Host "  2. Start Python server: python -m noray.main (or uvicorn api.main:app)"
Write-Host "  3. Start Next.js frontend: cd frontend && npm run dev"
