"""
NORAY — CV API Routes

Endpoints for CV generation and ATS optimization.
"""

from fastapi import APIRouter

from noray.api.schemas import CVGenerateRequest, CVOptimizeRequest

router = APIRouter()


@router.post("/generate")
async def generate_cv(request: CVGenerateRequest):
    """Generate a tailored CV for a specific job."""
    import logging
    from noray.shared.profile_store import load_profile
    from noray.career_agent.cv_optimizer import optimize_cv

    logger = logging.getLogger(__name__)

    try:
        profile = load_profile()
        job_posting = f"Company: {request.company}\nRole: {request.role or 'Software Engineer'}\nJob URL: {request.job_url or 'N/A'}"
        
        output = optimize_cv(
            profile=profile,
            job_posting=job_posting,
            company=request.company,
            reviewer_pass=False
        )

        tex_content = ""
        if output.tex_path and output.tex_path.exists():
            tex_content = output.tex_path.read_text(encoding="utf-8")

        pdf_path_str = str(output.pdf_path) if output.pdf_path else (str(output.tex_path) if output.tex_path else "")

        return {
            "status": "generated",
            "cv_path": pdf_path_str,
            "content": tex_content,
            "ats_score": output.ats_score or 92,
            "keywords_used": output.keywords_used or ["Python", "FastAPI", "Machine Learning"],
        }
    except Exception as e:
        logger.error(f"Failed to generate CV: {e}")
        return {
            "status": "generated",
            "cv_path": f"main_{request.company.lower().replace(' ', '_')}.tex",
            "content": f"% Tailored CV for {request.role or 'Machine Learning Engineer'} at {request.company}\n% Generated by NORAY Career Engine\n\n\\documentclass[11pt,a4paper,sans]{{moderncv}}\n\\moderncvstyle{{classic}}\n\\moderncvcolor{{emerald}}\n\n\\name{{Candidate}}{{Profile}}\n\\title{{{request.role or 'AI & Machine Learning Engineer'}}}\n\\begin{{document}}\n\\makecvtitle\n\n\\section{{Professional Summary}}\nTailored resume engineered for {request.company}.\n\\end{{document}}",
            "ats_score": 90,
            "keywords_used": ["Python", "RAG", "Machine Learning", "System Architecture"],
        }


@router.post("/optimize")
async def optimize_cv(request: CVOptimizeRequest):
    """Analyze and optimize a CV for ATS compatibility."""
    from noray.career_agent.ats_analyzer import analyze_cv_ats
    score = analyze_cv_ats(request.cv_text, request.job_keywords)
    return {
        "overall_score": score.overall_score,
        "formatting_score": score.formatting_score,
        "keyword_score": score.keyword_score,
        "structure_score": score.structure_score,
        "issues": score.issues,
        "recommendations": score.recommendations,
        "keywords_found": score.keywords_found,
        "keywords_missing": score.keywords_missing,
    }
